### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by dbordak** [revan/Moustachio#1]
You state that the Chrome Extension has no requirements.

What about Chrome?

(more seriously there is probably a version limitation that might be useful to people using Chrome derivatives, like Opera)

**Comment by revan** [comment]
Users of Chrome derivatives don't need this application, as they probably have luxurious hipster moustaches of their own.

**Comment by dbordak** [comment]
You mean to say that Moustachio either:
- Pastes a hipster moustache (clearly not true), or
- Pastes a moustache that would not improve a face with a hipster moustache

I find this hard to believe.
